FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o worker geofence/worker.go

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y libc6

WORKDIR /app

COPY --from=builder /app/worker .

CMD ["./worker"]